### PR TITLE
Add support for watchify

### PR DESCRIPTION
**Pull request by jesstelford**
By not passing back any `fileData`, we trigger `module-dep`'s `readFile` function, which in turn emits the `'file'` event that is required by watchify to correctly trigger an `'update'` event, allowing us to rebuild.

(This was a doozy of digging through events to figure out!)

### CODE REVIEW

**Comment by jesstelford** [comment]
Actually, on further thought - does this actually achieve anything? Using watchify means that rebuilds are very fast due to a different caching mechanism used internally. And given this change forces rebuilding on every run, it wouldn't be useful as a cache across runs (or across modules that share the same cache key object).

Thoughts?

**Comment by martinheidegger** [comment]
Oh my...

the first thought that comes to mind is that watchify should use the new cache API ;). This PR though destroys all the value we get from the fs cache and I think we have to take a different approach to fix that.

**Comment by martinheidegger** [comment]
This is actually an issue in `module-deps`. I am preparing a PR to fix it.

**Comment by martinheidegger** [comment]
In case you didn't see it: I opened https://github.com/substack/module-deps/pull/127 that should fix this issue. It would be lovely if you could review/test it.

**Pull request closed without merging**
